# Generated by Django 5.0.3 on 2024-03-10 17:53

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "cid",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(10000),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                    ),
                ),
                (
                    "cname",
                    models.CharField(
                        max_length=25, validators=[courses.models.validate_persian]
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("فنی و مهندسی", "فنی و مهندسی"),
                            ("علوم پایه", "علوم پایه"),
                            ("ادبیات و علوم انسانی", "ادبیات و علوم انسانی"),
                            ("مدیریت و اقتصاد", "مدیریت و اقتصاد"),
                            ("کشاورزی", "کشاورزی"),
                            ("منابع طبیعی", "منابع طبیعی"),
                            ("دامپزشکی", "دامپزشکی"),
                            ("شیمی", "شیمی"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "credit",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
            ],
        ),
    ]
